// autogenerated from genswiftimages --in BRCodingExam/Assets.xcassets --out BRCodingExam/Images.swift

import UIKit

extension UIImage {
	
	static var cellGradientBackground: UIImage { return UIImage(named: #function)! }
	static var ic_close: UIImage { return UIImage(named: #function)! }
	static var ic_webBack: UIImage { return UIImage(named: #function)! }
	static var ic_webForward: UIImage { return UIImage(named: #function)! }
	static var ic_webRefresh: UIImage { return UIImage(named: #function)! }
	static var icon_map: UIImage { return UIImage(named: #function)! }
	static var tab_internets: UIImage { return UIImage(named: #function)! }
	static var tab_lunch: UIImage { return UIImage(named: #function)! }
}
