// autogenerated from genswiftstoryboards --in BRCodingExam/Base.lproj --out BRCodingExam/Storyboards.swift

import UIKit
import ExtraKit

enum StoryboardLunch {
	
	struct Detail: StoryboardScene {
		typealias StoryboardClass = RestaurantDetailViewController
		struct Segue: StoryboardSceneSegue {
		}
		let identifier = ("Detail", "Lunch")
	}
	struct List: StoryboardScene {
		typealias StoryboardClass = RestaurantsViewController
		struct Segue: StoryboardSceneSegue {
		}
		let identifier = ("List", "Lunch")
	}
}

