// autogenerated from genswiftstrings --in BRCodingExam/en.lproj/Localizable.strings --out BRCodingExam/Strings.swift

import UIKit

extension String {
	
	static var tab_internets: String { return #function.localized() }
}
